baseURL = "https://example.com/"
languageCode = "en-us"
title = "A Hugo theme for creating Webslides.js presentations"
disableKinds = ["sitemap", "RSS"]
theme = "hugo-cssslides"

[author]
name = "RCJacH"

[params]
